export const QUESTIONS_FETCHING_START = "QUESTIONS_FETCHING_START";
export const QUESTIONS_FETCHING_SUCCESS = "QUESTIONS_FETCHING_SUCCESS";
export const QUESTIONS_FETCHING_FAIL = "QUESTIONS_FETCHING_FAIL";

export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const STUDENT_SETUP = "STUDENT_SETUP";
export const USER_SIGNOUT = "USER_SIGNOUT";